steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'VITE_API_URL=${_VITE_API_URL}', '-t', '$_IMAGE_NAME', '.' ]
images:
- '$_IMAGE_NAME'
substitutions:
  _VITE_API_URL: 'http://localhost:4000/api'
  _IMAGE_NAME: 'gcr.io/my-project/my-image'
options:
  substitutionOption: ALLOW_LOOSE
