steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'VITE_API_URL=https://mathinova-backend-420478767625.us-central1.run.app/api', '-t', '$_IMAGE_NAME', '.']
images:
- '$_IMAGE_NAME'
