import React, { useEffect } from 'react';
import GlassCard from '../components/GlassCard';
import useTitle from '../hooks/useTitle';

const PrivacyPage: React.FC = () => {
    useTitle('Privacy Policy | Mathinova');

    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="min-h-screen bg-bg-obsidian pt-32 pb-20">
            <div className="container">
                <div className="max-w-4xl mx-auto">
                    <div className="mb-10 text-center">
                        <h1 className="text-4xl md:text-5xl font-black tracking-tight text-text-primary mb-4">Privacy <span className="gradient-text">Policy</span></h1>
                        <p className="text-text-muted font-medium">Last updated: February 18, 2022</p>
                    </div>

                    <GlassCard className="p-8 md:p-12 border-white/5 leading-relaxed">
                        <div className="prose-legal space-y-10 text-text-secondary">
                            <p>
                                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information 
                                when You use the Service and tells You about Your privacy rights and how the law protects You.
                            </p>
                            <p>
                                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection 
                                and use of information in accordance with this Privacy Policy.
                            </p>

                            <section className="space-y-6">
                                <h2 className="text-2xl font-bold text-text-primary border-b border-white/10 pb-2">Interpretation and Definitions</h2>
                                <div className="space-y-4">
                                    <h3 className="text-xl font-bold text-text-primary/90">Definitions</h3>
                                    <p>For the purposes of this Privacy Policy:</p>
                                    <ul className="list-disc pl-6 space-y-4">
                                        <li><strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.</li>
                                        <li><strong>Company:</strong> Refers to Innovent Engineering Solutions Pvt Ltd, Bengaluru, Karnataka 560008.</li>
                                        <li><strong>Cookies:</strong> Small files placed on Your device by a website, containing details of Your browsing history.</li>
                                        <li><strong>Device:</strong> Any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                                        <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
                                        <li><strong>Service:</strong> Refers to the Website (Mathinova).</li>
                                        <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or from the Service infrastructure.</li>
                                    </ul>
                                </div>
                            </section>

                            <section className="space-y-6">
                                <h2 className="text-2xl font-bold text-text-primary border-b border-white/10 pb-2">Collecting and Using Your Personal Data</h2>
                                <div className="space-y-4">
                                    <h3 className="text-xl font-bold text-text-primary/90">Types of Data Collected</h3>
                                    <p className="font-bold text-text-primary/80">Personal Data</p>
                                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information:</p>
                                    <ul className="list-disc pl-6 space-y-2">
                                        <li>Email address</li>
                                        <li>First name and last name</li>
                                        <li>Phone number</li>
                                        <li>Usage Data</li>
                                    </ul>

                                    <p className="font-bold text-text-primary/80 mt-6">Usage Data</p>
                                    <p>
                                        Usage Data may include information such as Your Device’s IP address, browser type, browser version, 
                                        the pages You visit, the time and date of Your visit, and other diagnostic data.
                                    </p>
                                </div>
                            </section>

                            <section className="space-y-6">
                                <h2 className="text-2xl font-bold text-text-primary border-b border-white/10 pb-2">Use of Your Personal Data</h2>
                                <p>The Company may use Personal Data for the following purposes:</p>
                                <ul className="list-disc pl-6 space-y-3">
                                    <li>To provide and maintain our Service, including monitoring usage.</li>
                                    <li>To manage Your Account and registration as a user.</li>
                                    <li>For the performance of a contract (purchases).</li>
                                    <li>To contact You regarding updates or informative communications.</li>
                                    <li>To provide news, special offers, and general information about other goods or services.</li>
                                    <li>To manage Your requests.</li>
                                </ul>
                            </section>

                            <section className="space-y-6">
                                <h2 className="text-2xl font-bold text-text-primary border-b border-white/10 pb-2">Security of Your Personal Data</h2>
                                <p>
                                    The security of Your Personal Data is important to Us, but remember that no method of transmission 
                                    over the Internet is 100% secure. While We strive to use commercially acceptable means to protect 
                                    Your Personal Data, We cannot guarantee its absolute security.
                                </p>
                            </section>

                            <section className="space-y-6">
                                <h2 className="text-2xl font-bold text-text-primary border-b border-white/10 pb-2">Contact Us</h2>
                                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                                <div className="bg-white/5 p-6 rounded-2xl border border-white/5">
                                    <p className="flex items-center gap-3">
                                        <span className="font-bold text-text-primary">Email:</span>
                                        <a href="mailto:support@mathinova.com" className="text-primary hover:underline">support@mathinova.com</a>
                                    </p>
                                </div>
                            </section>
                        </div>
                    </GlassCard>
                </div>
            </div>
        </div>
    );
};

export default PrivacyPage;
