import React, { useEffect } from 'react';
import GlassCard from '../components/GlassCard';
import useTitle from '../hooks/useTitle';

const PrivacyPage: React.FC = () => {
    useTitle('Privacy Policy | Mathinova');

    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="min-h-screen bg-bg-obsidian pt-32 pb-20">
            <div className="container">
                <div className="max-w-4xl mx-auto">
                    <div className="mb-10 text-center">
                        <h1 className="text-4xl md:text-5xl font-black tracking-tight text-text-primary mb-4">Privacy <span className="gradient-text">Policy</span></h1>
                        <p className="text-text-muted font-medium">Last updated: March 2026</p>
                    </div>

                    <GlassCard className="p-10 border-white/5 leading-relaxed">
                        <div className="prose-legal space-y-8 text-text-secondary">
                            <section className="space-y-4">
                                <h2 className="text-2xl font-bold text-text-primary">Interpretation and Definitions</h2>
                                <h3 className="text-xl font-bold text-text-primary/90 mt-4">Definitions</h3>
                                <ul className="list-disc pl-6 space-y-2">
                                    <li><strong>Account:</strong> A unique account created for You to access our Service.</li>
                                    <li><strong>Company:</strong> Refers to Innovent Engineering Solutions Pvt Ltd, Bengaluru.</li>
                                    <li><strong>Cookies:</strong> Small files placed on Your device containing browsing history details.</li>
                                    <li><strong>Personal Data:</strong> Any information relating to an identified or identifiable individual.</li>
                                    <li><strong>Service:</strong> Refers to the Mathinova Website.</li>
                                    <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service.</li>
                                </ul>
                            </section>

                            <section className="space-y-4">
                                <h2 className="text-2xl font-bold text-text-primary">Collecting and Using Your Personal Data</h2>
                                <h3 className="text-xl font-bold text-text-primary/90">Types of Data Collected</h3>
                                <p>While using Our Service, We may ask You to provide certain personally identifiable information:</p>
                                <ul className="list-disc pl-6 space-y-2">
                                    <li>Email address</li>
                                    <li>First name and last name</li>
                                    <li>Phone number</li>
                                    <li>Usage Data (IP, browser type, device info)</li>
                                </ul>
                            </section>

                            <section className="space-y-4">
                                <h2 className="text-2xl font-bold text-text-primary">Use of Your Personal Data</h2>
                                <p>The Company may use Personal Data for the following purposes:</p>
                                <ul className="list-disc pl-6 space-y-2">
                                    <li>To provide and maintain our Service.</li>
                                    <li>To manage Your Account.</li>
                                    <li>For the performance of a contract (purchases).</li>
                                    <li>To contact You via email, calls, or SMS regarding updates.</li>
                                    <li>To provide You with news, special offers, and general info.</li>
                                </ul>
                            </section>

                            <section className="space-y-4">
                                <h2 className="text-2xl font-bold text-text-primary">Security of Your Personal Data</h2>
                                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                            </section>

                            <section className="space-y-4">
                                <h2 className="text-2xl font-bold text-text-primary">Contact Us</h2>
                                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                                <ul className="list-disc pl-6">
                                    <li>By email: support@mathinova.com</li>
                                </ul>
                            </section>
                        </div>
                    </GlassCard>
                </div>
            </div>
        </div>
    );
};

export default PrivacyPage;
